### ISSUE TITLE
`Import binascii` missing from README examples

### ISSUE THREAD

**Issue by Uxio0** [ebellocchia/bip_utils#1]
Hi!

I noticed that in some of the examples you are using `binascii.unhexlify()`, but `import binascii` is missing. Otherwise you could use `bytes.fromhex()`, that requires no import.

Really good job! Kind regards

**Comment by ebellocchia** [comment]
Hi, 
thanks for the comment. Yes I know, actually I've just put the imports for the _bip_utils_ package, neglecting the standard ones. Anyway it's a good suggestion, I'll fix it.

Regards

**Comment by Uxio0** [comment]
Thank you. I'm currently using your project for Ethereum Hd wallets https://github.com/gnosis/safe-cli/blob/master/safe_cli/ethereum_hd_wallet.py

I send you a PR to add Ethereum for Bip44 https://github.com/ebellocchia/bip_utils/pull/2
