### ISSUE TITLE
How to use uncompressed public key mode for derivation?

### ISSUE THREAD

**Issue by Anynomouss** [ebellocchia/bip_utils#103]
Is there a way to set the public key mode to uncompressed using? :
`Bip32Slip10Secp256k1.FromSeedAndPath(seed_bytes, path)`

Alternatively, is there a way to get uncompressed public key from the compressed one, and use it to derive an address using?:
`Bip32Slip10Secp256k1.FromPublicKey`

I can use the code here to convert the compressed public key to uncompressed, but prefer to use bip_utils itself.
https://stackoverflow.com/questions/43629265/deriving-an-ecdsa-uncompressed-public-key-from-a-compressed-one

**Comment by ebellocchia** [comment]
You can get/print a public key in both formats:

    print(bip44_ctx.PublicKey().RawCompressed().ToHex())
    print(bip44_ctx.PublicKey().RawUncompressed().ToHex())

    bip44_ctx.PublicKey().RawCompressed().ToBytes()
    bip44_ctx.PublicKey().RawUncompressed().ToBytes()

**Comment by Anynomouss** [comment]
Thanks, should have guessed that myself, I am not clear minded today.
