### ISSUE TITLE
Language error when using ElectrumV1MnemonicDecoder

### ISSUE THREAD

**Issue by Anynomouss** [ebellocchia/bip_utils#110]
When I try to use the _ElectrumV1MnemonicDecoder(my_mnemonic)_ class, I get the error
`TypeError: Language is not an enumerative of Bip39Languages`

I also tried with a newly generated mnemonic:
```
v1_standard_mnemonic = ElectrumV1MnemonicGenerator().FromWordsNumber(ElectrumV1WordsNum.WORDS_NUM_12)
my_mnemonic = v1_standard_mnemonic.ToStr()
ElectrumV1MnemonicDecoder(my_mnemonic)
```
If I understood the description of the _ElectrumV1MnemonicDecoder_, feeding it a mnemnonic string should be sufficient. 
Am I overlooking something?

**Comment by ebellocchia** [comment]
Hi, you have to pass the language when constructing the class and the mnemonic when you call the `Decode` function, so:

`ElectrumV1MnemonicDecoder().Decode(mnemonic)`

**Comment by Anynomouss** [comment]
With some further testing of round conversions I still encounter issues when converting from a string mnemonic.
The below lines reproduce the error I encountered. When going from a mnemonic object - > string -> seed, I get a different error then when I directly get the seed from the mnemonic oject:

```
v1_standard_mnemonic = ElectrumV1MnemonicGenerator().FromWordsNumber(ElectrumV1WordsNum.WORDS_NUM_12)
my_mnemonic = v1_standard_mnemonic.ToStr()
## Below line produces correct seed_bytes
v1_seed_bytes_correct = ElectrumV1SeedGenerator(v1_standard_mnemonic).Generate()
## Below line produces a different, shorter seed bytes that trows an error
v1_seed_bytes_not_correct = ElectrumV1MnemonicDecoder().Decode(my_mnemonic)
print("Correct seed bytes: {}".format(v1_seed_bytes_correct))
print("Incorrect seed bytes: {}".format(v1_seed_bytes_not_correct))
v1_standard_mnemonic = ElectrumV1.FromSeed(v1_seed_bytes_correct )
v1_standard_mnemonic = ElectrumV1.FromSeed(v1_seed_bytes_not_correct)
```
The last line that use the mnemonic as string as input give the error _"ValueError: Invalid private key bytes"_

**Comment by ebellocchia** [comment]
The decoder class decodes the mnemonic and gives you back the entropy bytes (which is 16 bytes long), not the seed. So, what you are doing is wrong.

**Comment by Anynomouss** [comment]
My bad, I thought entropy_bytes and seed_bytes were the same. I will read up on the documentation.
