### ISSUE TITLE
Update PyPi to latest changes

### ISSUE THREAD

**Issue by mehdiirh** [ebellocchia/bip_utils#112]
Hello, Emanuele.

Thank you for your great work on this project.
would you please update PyPi to the latest version ( including coincurve==18.0.0 )?
It seems like it's not updated there yet, as it can't be installed in python3.11.3 ( coincurve==17.0.0 fails to install ).

Regards

**Comment by ebellocchia** [comment]
Hi,
ok no problem, I'll update it
