### ISSUE TITLE
Dependencies upgrade?

### ISSUE THREAD

**Issue by MementoRC** [ebellocchia/bip_utils#119]
Hello,
Would it be possible to upgrade the dependencies? I am trying to propose a conda-forge recipe, but certain package versions do not exist on conda-forge (like ecdas 0.15, only >-0.16)

Also, `coincurve` was recently upgraded to using the latest 0.4.1 version of `secp256k1` (v18.0.0 used an unreleased version of it)

My fork does not seem to indicate any issues with the upgraded requirements and the conda-forge recipe builds cleanly with the available conda-forge version of the requirements

Also, if you are interested in being a maintainer for the conda-forge recipe, let me know:
https://github.com/conda-forge/staged-recipes/pull/25061
Thx

**Comment by ebellocchia** [comment]
Yes, I need to update `coincurve` and `ed25519-blake2b` dependencies to support Python 3.12
I can update ECDSA >=0.16 if needed

**Comment by MementoRC** [comment]
Great.

FYI,  I ran the recipe without issues on win/osx/linux with:
    - cbor2 =5.6.*
    - coincurve >=19,<20
    - crcmod ==1.7
    - ecdsa >=0.18
    - ed25519-blake2b ==1.4
    - py-sr25519-bindings >=0.2.0
    - pycryptodome >=3.20
    - pynacl >=1.5
    - python

Thank you

**Comment by ebellocchia** [comment]
Just to recap, these are the current dependencies after my last update:

```
cbor2~=5.1
coincurve>=15.0.1,<20.0.0
crcmod~=1.7
ecdsa~=0.15
ed25519-blake2b>=1.4.1,<2.0.0
pycryptodome~=3.6
pynacl~=1.4
py-sr25519-bindings>=0.1.3,<2.0.0
```

So, is it ok if I just put 0.16 for `ecdsa`?

**Comment by MementoRC** [comment]
@ebellocchia Yes, that will work for the conda recipe. Note that we are working on an unresolved issue with `coincurve 19.0.0` on windows: https://github.com/ofek/coincurve/issues/133
