### ISSUE TITLE
Add support for BITCOIN_CASH_ABC

### ISSUE THREAD

**Issue by X13454** [ebellocchia/bip_utils#12]
Hello,

A BITCOIN_CASH_ABC entry could be added to the following (and where else necessary):
https://github.com/ebellocchia/bip_utils/blob/3366233741c91348892c299211a776564cb2b322/bip_utils/bip/bip44_base.py#L106
Bip44Coins.BITCOIN_CASH_ABC: 1899

1899 is consistent with the official web wallet (cashtab) and ElectrumABC
See: https://github.com/Bitcoin-ABC/ElectrumABC/pull/62

**Comment by ebellocchia** [comment]
Hello,
ok thank you, I can add it in future releases.

Kind Regards,
Emanuele
