### ISSUE TITLE
Generate correct taproot addresses for both wallets

### ISSUE THREAD

**Issue by jjhesk** [ebellocchia/bip_utils#121]
I am looking to solve the problems of finding the correct P2TR (m/86'/0'/0'/0) address starting from the given 12 words mnemonic.

Generate to bitcoin address with P2TR standard as mentioned works of [OKX wallet](https://github.com/okx/js-wallet-sdk/blob/main/packages/coin-bitcoin/src/taproot.ts) and the works of [unisats wallet](https://github.com/unisat-wallet/extension) they both have different ways to generate the bitcoin taproot address. 

The basic concept:
A pay-to-taproot (P2TR), also known as a Taproot or Bech32m address, is the most recent and advanced bitcoin address format. Taproot introduces more advanced security, privacy, flexibility and scaling to bitcoin. Like SegWit, Taproot addresses are opt-in and not currently widely supported. Taproot adoption can be tracked [here](https://en.bitcoin.it/wiki/Bech32_adoption).

Benefits of Taproot include the ability to use Schnorr Signatures, offering better security, lower fees, and more flexible [multi-key](https://bitcoin.design/guide/private-key-management/multi-key/) transactions. Multi-key addresses using P2TR look the same as single-key addresses giving users of multi-key increased privacy. Taproot also enables more advanced scripting, enabling more complex smart contracts to be built on bitcoin.

Taproot addresses start with bc1p with total length of 62 and are case insensitive. [specification](https://en.bitcoin.it/wiki/Bech32)

step 2:
After I have done studying the generation mechanism,  I try to integrate the python coding into the [hd-wallet](https://github.com/meherett/python-hdwallet) repo for better code management. 

I want to express my gratitude for the excellent package you have created. I extensively used your package code to develop a wallet package in EXX.

**Comment by ebellocchia** [comment]
Hi, do you know in which way that wallet generates the address differently?

**Comment by ebellocchia** [comment]
Hi,
I made a test using the "typical" 12-word mnemonic `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about` with OKX, Unisats and bip_utils. They all generated the same Taproot address `bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr` for that mnemonic, so I don't understand why you saw a difference.

**Comment by ebellocchia** [comment]
Ok, maybe it was a bug

**Comment by tomguluson92** [comment]
> Hi, I made a test using the "typical" 12-word mnemonic `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about` with OKX, Unisats and bip_utils. They all generated the same Taproot address `bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr` for that mnemonic, so I don't understand why you saw a difference.
> 
> <img alt="Screenshot 2024-02-09 113411" width="317" src="https://private-user-images.githubusercontent.com/54482000/303624636-37383298-4bee-4dab-b84c-f55f2f7879ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTAzNjcsIm5iZiI6MTcyMzcxMDA2NywicGF0aCI6Ii81NDQ4MjAwMC8zMDM2MjQ2MzYtMzczODMyOTgtNGJlZS00ZGFiLWI4NGMtZjU1ZjJmNzg3OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Y2RlZDEyZGJhMGZjNjEzYTBhOWMyNjViN2FjOGU2NDkyZTU2NjFjY2YzY2NkZDZkNjUzOTRmMDFiMjFhNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bl9OMaOuucO_sNyRJ2Qk6q8yWWlihxiMPq-wBb-qIXs"> <img alt="Screenshot 2024-02-09 113703" width="391" src="https://private-user-images.githubusercontent.com/54482000/303625005-544d7f8c-4359-4b56-85f3-da4c9ee08667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTAzNjcsIm5iZiI6MTcyMzcxMDA2NywicGF0aCI6Ii81NDQ4MjAwMC8zMDM2MjUwMDUtNTQ0ZDdmOGMtNDM1OS00YjU2LTg1ZjMtZGE0YzllZTA4NjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNjk3ZGVhZWMyZDEwNWE1ZTlmNDVhMGYxZjU0NTFkNmIyZDM2Nzg2NTI4NjBjNzc4OTE4YjJhNWEzMDJiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsxHdhUkfsc5fxplp8wPR3JjeadLOK-WY8HxKD636Rg"> <img alt="Screenshot 2024-02-09 113526" width="584" src="https://private-user-images.githubusercontent.com/54482000/303624656-f208d9f8-892d-47eb-bae5-bee4c37811d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTAzNjcsIm5iZiI6MTcyMzcxMDA2NywicGF0aCI6Ii81NDQ4MjAwMC8zMDM2MjQ2NTYtZjIwOGQ5ZjgtODkyZC00N2ViLWJhZTUtYmVlNGMzNzgxMWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDhiZWE1ODBiZGJhYjE4NzYzYjJkMmJmZDcyM2QyYzRiZGRiMDNlYzViODJkYjRiNzZhYTYyMTZiMDgwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEAzSFQFd5MsKUw11Fb-4EQDsaMWQuvL_oCDVcTXAbY">

Could you please share the code example? Appreciated for your help~
