### ISSUE TITLE
Building wheel for ed25519-blake2b (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by HassanVaezzadeh** [ebellocchia/bip_utils#122]
Hi
I have a problem with` bip_utils` lib during installation! I used many ways and also downgrade my python to older versions. But the problem is still there! What can I do with this error?

**Comment by ebellocchia** [comment]
Hi,
first of all this depends on the `ed25519-blake2b` library, not on `bip_utils`.
Anyway, to build the library you need to have a C compiler installed. On Linux and MacOS usually there is no problem building it, it's on Windows that it could be tricky.
For this reason, I created some pre-built wheels [here](https://github.com/ebellocchia/bip_utils/tree/master/libs_wheels/ed25519_blake2b), you can download the one you need and install it using `pip`.
I'm also considering forking the library to release the pre-built wheels directly on pypi for the future.

Regards
Emanuele

**Comment by MementoRC** [comment]
Shameless plug: Both packages are soon going to be on `conda-forge`
