### ISSUE TITLE
Bug in generating Aptos addresses

### ISSUE THREAD

**Issue by b1tboy** [ebellocchia/bip_utils#125]
When generating Aptos addresses, if it starts with 0, it will be omitted
Mnemonic string: gospel virtual copy art bubble spider slender arctic trash roast case afford
Addresses:
0 - 0x65159f3d58b26d2c60c296c2a935b1c0b81da34d7ea686f4e74fe45312397b2 - 0x05a9ca341b6dc160ce32505ec9dd3e1fd538dc3cd05e5db0b9455f69ffde96e9
1 - 0xf55445b6577a3141771898c420f7340a560e5e64b4a1479a8e830a942c5364ba - 0xe34f437bc0c4359375a700ec50fd8533f010cb71ceebd39082ba329e5aaa483b
2 - 0xd40bce456125b2e289ab3f6cccdb6b6f8821d7ea634adf00a6a0797d0153d505 - 0xc10b9a83123358c3ad81016539ea4593381d8f13bb927a06bc60b6e6aff66167

**Comment by ebellocchia** [comment]
Hi, thanks for the finding, I'll fix it

**Comment by ebellocchia** [comment]
It's strange because I purposely stripped the starting zeroes in the code, so probably I noticed this behavior in some wallets

**Comment by ebellocchia** [comment]
I purposely removed the leading zeroes from the address because that's the behavior of TrustWallet, so I'm a little bit confused if keeping them or not

**Comment by b1tboy** [comment]
onekey or okx web3 wallet is better to use
