### ISSUE TITLE
Not generating correct BIP86 addresses for regtest

### ISSUE THREAD

**Issue by jahvi** [ebellocchia/bip_utils#126]
I'm trying to generate addresses from a MNEMONIC for a wallet using Bitcoin regtest but I haven't been able to generate the addresses I'm expecting. Here's what I'm using:

```python
seed_bytes = Bip39SeedGenerator(os.getenv("MNEMONIC")).Generate()
bip86_mst_ctx = Bip86.FromSeed(seed_bytes, Bip86Coins.BITCOIN_TESTNET)

bip86_acc_ctx = bip86_mst_ctx.Purpose().Coin().Account(0)

max_address_to_check = 20

# Derive BIP86 chain keys: m/86'/1'/0'/0
bip86_chg_ctx = bip86_acc_ctx.Change(Bip44Changes.CHAIN_EXT)

# Derive addresses: m/86'/1'/0'/0/i
for i in range(max_address_to_check):
    bip86_addr_ctx = bip86_chg_ctx.AddressIndex(i)
    print(bip86_addr_ctx.PublicKey().ToAddress())

# Derive addresses: m/86'/1'/0'/1/i
bip86_chg_ctx = bip86_acc_ctx.Change(Bip44Changes.CHAIN_INT)

for i in range(max_address_to_check):
    bip86_addr_ctx = bip86_chg_ctx.AddressIndex(i)
    print(bip86_addr_ctx.PublicKey().ToAddress())
```

The code prints out addresses that are not correct, if I use this tool and select "BTC (Bitcoin Regtest, Native SegWit, BIP84)" in the dropdown then the address is generates for the same mnemonic and path "m/86'/1'/0'/0" are the ones I expect however I'm not sure what it's doing differently:
https://gugger.guru/cryptography-toolkit/#!/hd-wallet

I have a feeling it's something todo with regtest but I haven't been able to figure it out, I haven't had any issues using mainnet with the same code (just changing `Bip86Coins.BITCOIN_TESTNET` to `BITCOIN`). Any advice on what to do?

Thanks.

**Comment by ebellocchia** [comment]
I used `tb1` as prefix for testnet addresses, I think it's just that

**Comment by jahvi** [comment]
I see, it looks like the addresses are very different though, eg: when I use this mnemonic:
`network elevator file brisk upon squeeze text age teach resist twice grid`

I expect the address for `m/86'/0'/0'/0/0` to be:
`bcrt1pu5fhctu6luwhhde7re97xxwqnpqhwc7ac6ter35xt9zer2stlwsqllxaq2`

But it shows:
`tb1pg7qmd8effv97nzq48g0k5k7ezqc8a5vwdlehzk4sl77ce9xa0axssnlyfn`

**Comment by ebellocchia** [comment]
That's normal, the encoding changes if zou change the prefix.
You can change the prefix like this and you'll get the same addresses of the website you linked:

```
mnemonic = "pilot gun beef rug chalk search foam pen achieve powder suggest demand"
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
bip86_mst_ctx = Bip86.FromSeed(seed_bytes, Bip86Coins.BITCOIN_TESTNET)

bip86_acc_ctx = bip86_mst_ctx.Purpose().Coin().Account(0)

max_address_to_check = 1

# Derive BIP86 chain keys: m/86'/1'/0'/0
bip86_chg_ctx = bip86_acc_ctx.Change(Bip44Changes.CHAIN_EXT)

# Derive addresses: m/86'/1'/0'/0/i
for i in range(max_address_to_check):
    bip86_addr_ctx = bip86_chg_ctx.AddressIndex(i)
    print(
        P2TRAddrEncoder.EncodeKey(
            bip86_addr_ctx.PublicKey().RawCompressed().ToBytes(),
            hrp="bc"
        )
    )
```

I can put the correct prefix, but that

**Comment by jahvi** [comment]
Thanks, you have to change the dropbox in the top right to change to regstest:

![Screenshot 2024-04-13 at 20 24 50](https://github.com/ebellocchia/bip_utils/assets/661330/635c1e4f-b529-4e55-9575-28b324d7ec41)

But I tried your solution and it worked by using `Bip86Coins.BITCOIN` AND `hrp="bcrt"` so it might be worth having another  enum for regtest.

**Comment by jahvi** [comment]
Slightly unrelated but how am I able to get the derivation path for: `m/86'/1'/0'/0/0` instead?

**Comment by ebellocchia** [comment]
Yes I selected it and got bc1

**Comment by ebellocchia** [comment]
I think you are making some confusion because everythign is fine.
If I select regtest I get `bcrt1pg7qmd8effv97nzq48g0k5k7ezqc8a5vwdlehzk4sl77ce9xa0axsa24zuf` as address as you can see here:

![Screenshot 2024-04-13 214246](https://github.com/ebellocchia/bip_utils/assets/54482000/65230a59-afcd-4045-a9f2-46628b4f4d52)

The derivation path is `m/86'/1'/0'/0/0` and it shall have the `1'` because it's a testnet, I don't know why you generated it with `0'`

And by modifying the prefix in my code I get exactly that address:

```
for i in range(max_address_to_check):
    bip86_addr_ctx = bip86_chg_ctx.AddressIndex(i)
    # Print: bcrt1pg7qmd8effv97nzq48g0k5k7ezqc8a5vwdlehzk4sl77ce9xa0axsa24zuf
    print(
        P2TRAddrEncoder.EncodeKey(
            bip86_addr_ctx.PublicKey().RawCompressed().ToBytes(),
            hrp="bcrt"
        )
    )
```

If you want to use `m/86'/0'/0'/0/0` and get `bcrt1pu5fhctu6luwhhde7re97xxwqnpqhwc7ac6ter35xt9zer2stlwsqllxaq2`, then you have to use `Bip86Coins.BITCOIN` because the testnet has 1 as coin index:

```
mnemonic = "network elevator file brisk upon squeeze text age teach resist twice grid"
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
bip86_mst_ctx = Bip86.FromSeed(seed_bytes, Bip86Coins.BITCOIN)

bip86_acc_ctx = bip86_mst_ctx.Purpose().Coin().Account(0)

max_address_to_check = 1

# Derive BIP86 chain keys: m/86'/1'/0'/0
bip86_chg_ctx = bip86_acc_ctx.Change(Bip44Changes.CHAIN_EXT)

# Derive addresses: m/86'/1'/0'/0/i
for i in range(max_address_to_check):
    bip86_addr_ctx = bip86_chg_ctx.AddressIndex(i)
    # Print: bcrt1pu5fhctu6luwhhde7re97xxwqnpqhwc7ac6ter35xt9zer2stlwsqllxaq2
    print(
        P2TRAddrEncoder.EncodeKey(
            bip86_addr_ctx.PublicKey().RawCompressed().ToBytes(),
            hrp="bcrt"
        )
    )
```

**Comment by jahvi** [comment]
Yes I deleted my previous comments because it does look like it works as expected by using the `P2TRAddrEncoder.EncodeKey` method you suggested.

But I think it's worth adding a `Bip86Coins.BITCOIN_REGTEST` enum so this is handled by the library and you can get the correct address with `bip86_addr_ctx.PublicKey().ToAddress()`.

**Comment by ebellocchia** [comment]
Yes sure I will add it
