### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EtherForge** [ebellocchia/bip_utils#136]
Hi all! I have an error:
![Скриншот 29-06-2024 184800](https://github.com/ebellocchia/bip_utils/assets/142614303/a943c4a3-31fb-4ca5-b412-cb93a72064f5)
Python - 3.10
Pip - 22.3.1
Pip installed modules:
PyQt5==5.15.7
requests==2.31.0
python-dotenv==1.0.0
But bip-utils==2.3.0 doesn't installing. Error on screenshot.

**Comment by EtherForge** [comment]
I'm trying to install bip by **pip install bip-utils==2.3.0**, i will try installing from github now, but i think it don't gave results.

**Comment by EtherForge** [comment]
![Скриншот 29-06-2024 200252](https://github.com/ebellocchia/bip_utils/assets/142614303/f786dfa2-45cc-4cff-9dfd-28b907bab225)
Now, it's look like this

**Comment by ebellocchia** [comment]
As written in the output, it's not related to my library but to the ed25519-blake2b one. It happens only on Windows and it's due to a missing C/C++ build environment.
You can use some pre-build wheels from [here](https://github.com/ebellocchia/bip_utils/tree/master/libs_wheels)

**Comment by EtherForge** [comment]
Thank you!
