### ISSUE TITLE
ANSI C language implementation

### ISSUE THREAD

**Issue by sfhacker** [ebellocchia/bip_utils#14]
Ciao.

Thanks for making available this awesome project.
Unfortunately, my python skills are basic and poor.
I was wondering if we are aware of a similar project to this one (particularly BIP 44/49/84) but implemented in C/C++ language?
Any pointers would be greatly appreciated.

Cheers.

**Comment by ebellocchia** [comment]
Hello,
you can check the Ledger or Trezor repos. In alternative, sometimes I check the TrustWallet repo to check how things are implemented: [https://github.com/trustwallet/wallet-core](https://github.com/trustwallet/wallet-core)

Regards
