### ISSUE TITLE
Validate function in Bip39MnemonicValidator maybe misfunction...

### ISSUE THREAD

**Issue by CryptoCoinLab** [ebellocchia/bip_utils#142]
from bip_utils import Bip39MnemonicGenerator, Bip39MnemonicValidator, Bip39Languages

def generate_and_validate_mnemonic():

	mnemonic = Bip39MnemonicGenerator(Bip39Languages.ENGLISH).FromWordsNumber(12).ToStr()
	print(f"mnemonic: {mnemonic}")
	
	is_valid = Bip39MnemonicValidator().IsValid(mnemonic)
	print(f"IsValid:  {'Yes' if is_valid else 'No'}")

	is_valid = Bip39MnemonicValidator().Validate(mnemonic)
	print(f"Validate: {'Yes' if is_valid else 'No'}")

if __name__ == "__main__":
	generate_and_validate_mnemonic()

The result is as following:

mnemonic: flush short theory sea fury hope release fatal smooth brown arrive gloom
IsValid:  Yes
Validate: No

**Comment by ebellocchia** [comment]
Thanks, I'll take a look

**Comment by ebellocchia** [comment]
Hi,
The `IsValid` method return a boolean indicating if the mnemonic is valid or not.
The `Validate` method is similar but with exceptions, so it doesn't return anything but it's triggering an exception if the mnemonic is not valid. That's why you get `False` (the return value is always `None`).

**Comment by CryptoCoinLab** [comment]
understood
