### ISSUE TITLE
Support for Solana ?

### ISSUE THREAD

**Issue by philogicae** [ebellocchia/bip_utils#19]
Hi,
First of all thank you, I find your repo very useful, great job !
I see in the doc Solana is supported, but Bip44Coins.SOLANA is missing. Bip32Secp256k1 also.
I guess the doc is outdated ?

**Comment by ebellocchia** [comment]
Hi,
I've just added the support for Ed25519/Nist256p1 curves and some coins that are based on those curves (Solana is one of the coins). This will be included in the release 2.0.0, but I still want to improve something before creating it. So, if you need it right now, you have to checkout the repo and install it manually.
The last release (1.11.1) just supports Secp256k1-based coins.

Regards,
Emanuele

**Comment by philogicae** [comment]
Wow fast answer ! Thank you again for your work, I will do that.
