### ISSUE TITLE
no work code

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#20]
my code not work. whu?
`
from bip_utils import Bip39SeedGenerator, Bip39EntropyGenerator,Bip39Languages, Bip39MnemonicGenerator, Bip39WordsNum, Bip39Languages, Bip44, Bip44Coins, Bip44Changes, Bip32, Bip32Utils

mnemonic = Bip39MnemonicGenerator().FromWordsNumber(Bip39WordsNum(12))
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
bip32_ctx = Bip32.FromSeed(seed_bytes)
bip32_ctx_ex = bip32_ctx.DerivePath("0'/0'/0")
bip32_addr:str = bip32_ctx_ex.PublicKey().ToAddress()
`

**Comment by ebellocchia** [comment]
Hello,
I run the code exactly as you wrote it and I didn't get any error. Could you explain me the problem you are facing?

Thanks

**Comment by Noname400** [comment]
I found the reason.
pip3 install ecdsa [gmpy2]
I tried to calm things down with ecdsa [gmpy2].
in version 1.6 it worked
in newer versions it gives a bunch of errors

**Comment by ebellocchia** [comment]
Hello,
thanks for the information, I was just installing ecdsa without gmpy2

Regards,
Emanuele
