### ISSUE TITLE
hash160

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#23]
1.How can I get HASH 160 instead of the address from the public key?

**Comment by ebellocchia** [comment]
Hi,
you can use the function *CryptoUtils.Hash160* importing it from *bip_utils.utils* (it's not exported externally), passing the public key bytes as parameters e.g. 

    CryptoUtils.Hash160(pub_key.RawCompressed().ToBytes())

Regards,
Emanuele

**Comment by Noname400** [comment]
work. THX
