### ISSUE TITLE
hardened  bip44

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#25]
How do I get a hard key?

**Comment by ebellocchia** [comment]
Only in Bip32 you can specify if using hardened or not hardened derivation.

In Bip44 this is determined by the spec and cannot be changed. The Bip44 path is:

    m / purpose' / coin_type' / account' / change / address_index

As you can see, hardened derivation is automatically used for _purpose_, _coin type_ and _account_ levels. Not-hardened derivation is used for _change_ and _address index_ levels.

If ed25519 curve is used, only hardened derivation is supported so the path is:

    m / purpose' / coin_type' / account' / change' / address_index'

This structure is mandatory from BIP44 and cannot be changed. The library takes care of deriving the levels correctly.

**Comment by Noname400** [comment]
ерч
