### ISSUE TITLE
update pypi for install

### ISSUE THREAD

**Issue by aleixisp** [ebellocchia/bip_utils#26]
I'm installing bip_utils using pipenv, which pulls the package prom pypi, I think the package is not well deployed, since I'm getting the latest version (1.11.1) but with an outdated package 

`pipenv install bip_utils==1.11.1`

####Current coins supported if installed through pypi

Coin | Main net enum | Test net enum
-- | -- | --
Bitcoin | Bip44Coins.BITCOIN | Bip44Coins.BITCOIN_TESTNET
Bitcoin Cash | Bip44Coins.BITCOIN_CASH | Bip44Coins.BITCOIN_CASH_TESTNET
BitcoinSV | Bip44Coins.BITCOIN_SV | Bip44Coins.BITCOIN_SV_TESTNET
Litecoin | Bip44Coins.LITECOIN | Bip44Coins.LITECOIN_TESTNET
Dogecoin | Bip44Coins.DOGECOIN | Bip44Coins.DOGECOIN_TESTNET
Dash | Bip44Coins.DASH | Bip44Coins.DASH_TESTNET
Zcash | Bip44Coins.ZCASH | Bip44Coins.ZCASH_TESTNET
Ethereum | Bip44Coins.ETHEREUM | -
Ethereum Classic | Bip44Coins.ETHEREUM_CLASSIC | -
Ripple | Bip44Coins.RIPPLE | -
Tron | Bip44Coins.TRON | -
VeChain | Bip44Coins.VECHAIN | -
Cosmos | Bip44Coins.COSMOS | -
Band Protocol | Bip44Coins.BAND_PROTOCOL | -
Kava | Bip44Coins.KAVA | -
IRIS Network | Bip44Coins.IRIS_NET | -
Terra | Bip44Coins.TERRA | -
Binance Chain | Bip44Coins.BINANCE_CHAIN | -
Binance Smart Chain | Bip44Coins.BINANCE_SMART_CHAIN | -
Avalanche C-Chain | Bip44Coins.AVAX_C_CHAIN | -
Avalanche X-Chain | Bip44Coins.AVAX_X_CHAIN | -
Avalanche P-Chain | Bip44Coins.AVAX_P_CHAIN | -
Polygon | Bip44Coins.POLYGON | -
Fantom Opera | Bip44Coins.FANTOM_OPERA | -
Harmony One (Metamask address) | Bip44Coins.HARMONY_ONE_METAMASK | -
Harmony One (Ethereum address) | Bip44Coins.HARMONY_ONE_ETH | -
Harmony One (Cosmos address) | Bip44Coins.HARMONY_ONE_ATOM | -
Huobi Chain | Bip44Coins.HUOBI_CHAIN | -
OKEx Chain (Ethereum address) | Bip44Coins.OKEX_CHAIN_ETH | -
OKEx Chain (Cosmos address) | Bip44Coins.OKEX_CHAIN_ATOM | -
OKEx Chain (Old Cosmos address before mainnet upgrade) | Bip44Coins.OKEX_CHAIN_ATOM_OLD | -

**Comment by ebellocchia** [comment]
Hello,
yes the last release (1.11.1) is a little bit outdated since I added lots of functionalities in the 2.0.0.
The 2.0.0 is not yet released so you don't find it on pypi, but it'll be released shortly. If you want to use it, you can clone the repo and install it from there.

Regards,
Emanuele

**Comment by aleixisp** [comment]
Thanks!
