### ISSUE TITLE
bip_utils/ecc/lib/ed25519_monero_lib.py does not get recognized as a package by setuptools

### ISSUE THREAD

**Issue by jimtje** [ebellocchia/bip_utils#29]
Hey there, I realize that the master branch is not ready for release so you may already know this but as currently configured, running 
```
python setup.py install 
```
will not install a working package because setuptools won't read a folder without 
```
__init__.py
``` 
as an importable package and so bip_utils/ecc/lib/ed25519_monero_lib.py won't be included when running the installation script. The simplest fix is to change  find_packages to find_namespace_packages in setup.py which will enable proper packaging. Alternatively, an empty 
```
__init__.py 
```

in the ecc/lib folder will also suffice. I have forked the repo and made the fix in a new branch and can submit a pull request if you'd like.

Also, it appears that the latest version of scalecodec changed its namespacing a bit as well, so in bip_utils/substrate/substrate_path.py the ScaleDecoder import needs to be changed to 
```
from scalecodec.base import ScaleDecoder
```
Likewise, I've forked and made the fix in the aforementioned new branch and can submit a pull request if you'd like. Cheers.

**Comment by ebellocchia** [comment]
Hello,
thanks for the findings. You're right, I forgot to place the *__init__.py* inside that folder.
If you've already made the changes yes, you can submit them of course.

Thanks
Emanuele

**Comment by ebellocchia** [comment]
Pull request merged, thanks!
