### ISSUE TITLE
Address generation not working

### ISSUE THREAD

**Issue by cryptoqube777** [ebellocchia/bip_utils#3]
Hi
After ibrary update code stopped working. **Complete code example** gives the following error:
`Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    bip_obj_acc = bip_obj_mst.Purpose().Coin().Account(0)
  
File "/home/sergey/Документы/2/bip_utils/bip/bip44.py", line 102, in Purpose
    return self._PurposeGeneric(self)

File "/home/sergey/Документы/2/bip_utils/bip/bip44_base.py", line 273, in _PurposeGeneric
    return cls(bip_obj.m_bip32.ChildKey(cls._GetPurpose()), bip_obj.m_coin_type)

File "/home/sergey/Документы/2/bip_utils/bip/bip32.py", line 226, in ChildKey
    return self.__CkdPriv(index) if not self.m_is_public else self.__CkdPub(index)

File "/home/sergey/Документы/2/bip_utils/bip/bip32.py", line 409, in __CkdPriv
    fprint      = self.FingerPrint(),

File "/home/sergey/Документы/2/bip_utils/bip/bip32.py", line 356, in FingerPrint
    return self.KeyIdentifier()[:Bip32Const.FINGERPRINT_BYTE_LEN]

File "/home/sergey/Документы/2/bip_utils/bip/bip32.py", line 348, in KeyIdentifier
    return CryptoUtils.Hash160(self.PublicKey().RawCompressed().ToBytes())

File "/home/sergey/Документы/2/bip_utils/bip/bip_keys.py", line 77, in RawCompressed
    return BipKeyBytes(self.m_bip32_obj.EcdsaPublicKey().to_string("compressed"))

TypeError: to_string() takes 1 positional argument but 2 were given
`
How to fix it?

**Comment by ebellocchia** [comment]
Hi, can you please write me the code snippet?

Thanks

**Comment by cryptoqube777** [comment]
The code snippet is directly from documentation. Last example named  **Complete code example** as follows:
```
from bip_utils import Bip39MnemonicGenerator, Bip39SeedGenerator, Bip44, Bip44Coins, Bip44Changes

# Generate random mnemonic
mnemonic = Bip39MnemonicGenerator.FromWordsNumber(12)
print("Mnemonic string: %s" % mnemonic)
# Generate seed from mnemonic
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()

# Generate BIP44 master keys
bip_obj_mst = Bip44.FromSeed(seed_bytes, Bip44Coins.BITCOIN)
# Print master key
print("Master key (bytes): %s" % bip_obj_mst.PrivateKey().Raw().ToHex())
print("Master key (extended): %s" % bip_obj_mst.PrivateKey().ToExtended())
print("Master key (WIF): %s" % bip_obj_mst.PrivateKey().ToWif())

# Generate BIP44 account keys: m/44'/0'/0'
bip_obj_acc = bip_obj_mst.Purpose().Coin().Account(0)
# Generate BIP44 chain keys: m/44'/0'/0'/0
bip_obj_chain = bip_obj_acc.Change(Bip44Changes.CHAIN_EXT)

# Generate the address pool (first 20 addresses): m/44'/0'/0'/0/i
for i in range(20):
    bip_obj_addr = bip_obj_chain.AddressIndex(i)
    print("%d. Address public key (extended): %s" % (i, bip_obj_addr.PublicKey().ToExtended()))
    print("%d. Address private key (extended): %s" % (i, bip_obj_addr.PrivateKey().ToExtended()))
    print("%d. Address: %s" % (i, bip_obj_addr.PublicKey().ToAddress()))
```

**Comment by ebellocchia** [comment]
Ok, I've just tried now and I didn't get any error (I also tried installing the library from scratch). Can you try uninstalling and installing again?

**Comment by cryptoqube777** [comment]
Just removed, reinstalled (current version is 1.4.0) and tried again. Same result, here are the links to screenshots.
https://ibb.co/h10HMFb
https://ibb.co/LQHYVNL

I'm using python 3.7.3 version.

**Comment by cryptoqube777** [comment]
really strange situation. I have tried same code under Windows 7, python 3.7.1 and it works fine. Under Debian 10 and Python 3.7.3 it fails. Any ideas about the reason of such behavior?

**Comment by ebellocchia** [comment]
Ok, I tried both on Windows and Xubuntu 20.04 and it was working.
The _to_string_ is a method of the _ecdsa_ module and the error states that I'm passing a parameter that it's not needed. So, I suppose that method signature is different in that case, but I don't understand exactly why.

**Comment by cryptoqube777** [comment]
I have found the issue. I had ecdsa==0.13.3 installed, although the latest one is 0.16. While installing bip_utils it wasn't updated. After updating to recent version everythin works great. 
So the issue can be closed.

**Comment by ebellocchia** [comment]
Ok, I'll update the minimum version required for the _ecdsa_ module in _setup.py_
Thank you very much
