### ISSUE TITLE
speed up

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#31]
to increase speed, maybe it is worth looking at other libraries?
ofek / match
Richardkiss / Pycoin

famous electrum wallet uses sec256k1 dll
but they all have a big drawback! They can't do everything you do
I ask you to add the use of swift libraries.

**Comment by Noname400** [comment]
https://github.com/ofek/coincurve

it is the ideal solution for increasing speed in all directions.
can you use it?
your library will be the fastest and most powerful in functionality.

**Comment by ebellocchia** [comment]
Hi,
yes I know that library and I've thought sometimes to use it, but it'll speed up only the coins based on secp256k1.
Anyway, I'll try to integrate it but I'm currently a little bit busy with private stuff, so I can start working on it at the end of this month.

Thanks,
Emanuele

**Comment by Noname400** [comment]
Hi. why can it be so?
1.Generation of the BIP32 key - 1 second 300 keys
2.Generation of the BIP44 key - 1 second 700 keys
although it should be the other way around since BIP44 comes from BIP32

**Comment by ebellocchia** [comment]
Hi, please share the code with which you got these timings, otherwise I cannot help you.

Thanks

**Comment by Noname400** [comment]
I took a cat from your examples

**Comment by Noname400** [comment]
Version 1.11.1
New version very slow

**Comment by ebellocchia** [comment]
I understand, but can you share the code anyway?

**Comment by Noname400** [comment]
OK. No problem

**Comment by ebellocchia** [comment]
Hi, I'll take a look to the coincurve library in the next days

**Comment by Noname400** [comment]
Super. I wait.

**Comment by Noname400** [comment]
Speed +50%

**Comment by Noname400** [comment]
Please chenge ver 1.11.1
Please unlock uncompress pub key.

**Comment by ebellocchia** [comment]
What does it mean "unlock uncompressed public key"?

**Comment by Noname400** [comment]
Generate Un Compress public key.

**Comment by Noname400** [comment]
I know this is contrary to bip39.  But please.

**Comment by ebellocchia** [comment]
I took a look at the v1.11.1 code and the uncompressed public key were already available, for example:

`bip44_mst.PublicKey().RawUncompressed().ToHex()`

**Comment by Noname400** [comment]
. ToAdreass()

**Comment by ebellocchia** [comment]
Hi,
I added coincurve, you can find it in the branch: [https://github.com/ebellocchia/bip_utils/tree/secp256k1_coincurve](https://github.com/ebellocchia/bip_utils/tree/secp256k1_coincurve)
You can try it, but I can see from the benchmark that it speeds up a lot (around +70%).

**Comment by Noname400** [comment]
have you unlocked the creation of an address from an uncompressed key?

**Comment by ebellocchia** [comment]
The address is automatically created from the uncompressed key for the coins that need it, you don't have to do anything.

**Comment by ebellocchia** [comment]
For example, in _eth_addr.py_:

`kekkak_hex` = ConvUtils.BytesToHexString(CryptoUtils.Kekkak256(pub_key_obj.RawUncompressed().ToBytes()[1:]))

It's selecting the uncompressed key automatically for Ethereum address.

**Comment by Noname400** [comment]
bip_addr_c = P2PKH.ToAddress(pk_c,net_addr_ver=b"\x00") #compres pub, OK
                            bip_addr_uc = P2PKH.ToAddress(pk_uc,net_addr_ver=b"\x00") #uncompress pub , ERROR

**Comment by ebellocchia** [comment]
Version v2.0.0 works both with compressed and uncompressed public keys, so you don't have to do anything:

    # Version v2.0.0 - Nothing to do
    import binascii
    from bip_utils import P2PKHAddr

    # Compressed key
    compr_key = binascii.unhexlify("02c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4")
    print(P2PKHAddr.EncodeKey(compr_key))

    # Uncompressed key, same
    uncompr_key = binascii.unhexlify("04c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4ec9654b17e30a8a5232078201ecf5cc702dfbb70266aecf16b1f81d85e6b9942")
    print(P2PKHAddr.EncodeKey(uncompr_key))

In version v1.11.1 you just have to convert your uncompressed key to the compressed one (it's one line of code):

    # Version v1.11.1
    import binascii
    import ecdsa
    from bip_utils import P2PKH

    # Compressed key
    compr_key = binascii.unhexlify("02c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4")
    print(P2PKH.ToAddress(compr_key))

    # Uncompressed key
    uncompr_key = binascii.unhexlify("04c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4ec9654b17e30a8a5232078201ecf5cc702dfbb70266aecf16b1f81d85e6b9942")
    # Convert to compressed key
    compr_key = ecdsa.VerifyingKey.from_string(uncompr_key, curve=ecdsa.curves.SECP256k1).to_string("compressed")
    # Print
    print(P2PKH.ToAddress(compr_key))

If you want to add the code for converting uncompressed to compressed in the *ToAddress* function feel free to do it. I cannot modify v1.11.1 anymore since the master branch is v2.0.0.

**Comment by ebellocchia** [comment]
Or, if you want to avoid using ecdsa, you can also compress the key by yourself the algorithm for compressing a key is very easy):

    # Version v1.11.1 - Without ecdsa
    import binascii
    from bip_utils import P2PKH

    # Function for compressing an uncompressed public key
    def compress_key(key: bytes) -> bytes:
        if key[0] != 0x04 or len(key) != 65:
            raise ValueError("Invalid uncompressed public key")

        x = key[1:33]
        y = int.from_bytes(key[33:65], "big")
        
        if y & 1:
            return b"\x03" + x
        else:
            return b"\x02" + x

    # Compressed key
    compr_key = binascii.unhexlify("02c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4")
    print(P2PKH.ToAddress(compr_key))

    # Uncompressed key
    uncompr_key = binascii.unhexlify("04c3d01cb07697dc5105013bea2e73a896b6019ec3c5ea2b97dba14ae4456439f4ec9654b17e30a8a5232078201ecf5cc702dfbb70266aecf16b1f81d85e6b9942")
    # Print
    print(P2PKH.ToAddress(compress_key(uncompr_key)))

**Comment by Noname400** [comment]
hi.
i download (https://github.com/ebellocchia/bip_utils/tree/secp256k1_coincurve)
install (python setup.py install) Instalation v.2.0.0 
run (python -m unittest discover)
ERROR:
ModuleNotFoundError: No module named 'ed25519_blake2b'

1. how to install version 1,11,1
2. how to remove the error

**Comment by ebellocchia** [comment]
You can use the master branch now, I merged it.
Anyway, use *pip* to avoid problems with dependencies:

`pip install .`

Inside the folder.
