### ISSUE TITLE
Add new coins

### ISSUE THREAD

**Issue by 123Serg** [ebellocchia/bip_utils#32]
Hello! First I want to say thank you for great job you've done. Please add support for these tokens (or some of them):
- Cardano
- Solana
- Polkadot
- Algorand
- Filecoin
- Internet computer
- Stellar
- FTX
- Theta
- Tezos
- EOS
- Hedera
- NEO

**Comment by ebellocchia** [comment]
Hi,
thank you. Most of the coins you listed are already present in the version 2.0.0, i.e.:
- Solana
- Polkadot
- Algorand
- Filecoin
- Stellar
- Theta
- Tezos
- NEO

FTX is a token as far as I know, so it uses the address of the underlying blockchain  (e.g. ETH).
Cardano is a coin I've wanted to add for a while but it's a little bit tricky (it has its own derivation algorithm), so I postponed it a little bit.

**Comment by 123Serg** [comment]
> Hi,
> 
> thank you. Most of the coins you listed are already present in the version 2.0.0, i.e.:
> 
> - Solana
> 
> - Polkadot
> 
> - Algorand
> 
> - Filecoin
> 
> - Stellar
> 
> - Theta
> 
> - Tezos
> 
> - NEO
> 
> 
> 
> FTX is a token as far as I know, so it uses the address of the underlying blockchain  (e.g. ETH).
> 
> Cardano is a coin I've wanted to add for a while but it's a little bit tricky (it has its own derivation algorithm), so I postponed it a little bit.

That's great, I didn't see 2.0 version. 

I'm using official Haskell script to convert seed to cardano addresses at the time, maybe it will help you:
https://github.com/input-output-hk/cardano-addresses 

Thank you.
