### ISSUE TITLE
Add cardano coin

### ISSUE THREAD

**Issue by antonon2018** [ebellocchia/bip_utils#37]
Hi, 
Can you add a cardano coin support into bip_utils ?
Thanks.

**Comment by ctrl-Felix** [comment]
What is the current status about Cardano? @ebellocchia

**Comment by ebellocchia** [comment]
Hi,
It's in progress here: [https://github.com/ebellocchia/bip_utils/tree/cardano](https://github.com/ebellocchia/bip_utils/tree/cardano)

I need to implement some some high-level classes to simplify the usage, but you can already use it for keys and addresses:

    from bip_utils import *

    # Seed
    mnemonic = "cost dash dress stove morning robust group affair stomach vacant route volume yellow salute laugh"
    seed_bytes = CardanoBip39SeedGenerator(mnemonic).Generate()
    # Cardano object
    cardano = CardanoIcarusBip32.FromSeed(seed_bytes)

    # Shelley
    shelley_addr = cardano.DerivePath("m/1852'/1815'/0'/0/0")
    print("Shelley addr priv: ", shelley_addr.PrivateKey().Raw().ToHex())
    print("Shelley addr pub:", shelley_addr.PublicKey().RawCompressed().ToHex()[2:] + shelley_addr.ChainCode().ToHex())

    shelley_sk = cardano.DerivePath("m/1852'/1815'/0'/2/0")
    print("Shelley sk priv", shelley_sk.PrivateKey().Raw().ToHex())
    print("Shelely sk pub", shelley_sk.PublicKey().RawCompressed().ToHex()[2:] + shelley_sk.ChainCode().ToHex())

    print("Shelley addr", AdaV3AddrEncoder.EncodeKey(shelley_addr.PublicKey().KeyObject(),
                                                     pub_skey=shelley_sk.PublicKey().KeyObject()))

    # Byron
    byron_addr = cardano.DerivePath("m/44'/1815'/0'/0/0")
    print("")
    print("Byron priv", byron_addr.PrivateKey().Raw().ToHex())
    print("Byron pub", byron_addr.PublicKey().RawCompressed().ToHex()[2:] + byron_addr.ChainCode().ToHex())
    print("Byron addr", AdaV2AddrEncoder.EncodeKey(byron_addr.PublicKey().KeyObject(),
                                                   chain_code=byron_addr.ChainCode()))

    # Ledger
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    ledger = Bip32Ed25519Kholaw.FromSeed(seed_bytes)

    ledger_addr = ledger.DerivePath("m/1852'/1815'/0'/0/1")
    ledger_sk = ledger.DerivePath("m/1852'/1815'/0'/2/0")

    print("")
    print("Ledger addr", AdaV3AddrEncoder.EncodeKey(ledger_addr.PublicKey().KeyObject(),
                                                    pub_skey=ledger_sk.PublicKey().KeyObject()))

**Comment by ebellocchia** [comment]
Hi, cardano branch has been merged to master
