### ISSUE TITLE
Derivation for non standart BIP 44 path

### ISSUE THREAD

**Issue by 123Serg** [ebellocchia/bip_utils#38]
Hey, I want to know how to derive addresses and keys from non standart BIP44 path. For example I want to derive seed for solana addresses in 4 paths:  1) m/44'/501'/0', 2) m/44'/501'/0'/0', 3) m/44'/501'/0/0, 4) m/0/0

For first path I'm using code from readme and it works fine:

```
import binascii
from bip_utils import Bip44Coins, Bip44

seed_bytes = binascii.unhexlify(b"5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4")

bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(0)
print(bip44_acc_ctx.PublicKey().ToAddress())
```

But how can I derive for second, third and fourth pathes? 
Thanks

**Comment by ebellocchia** [comment]
Hi,
so:
- number 2) is just the external chain, so you can just use _.Change(Bip44Changes.CHAIN_EXT)_ to derive it.
- number 3) cannot be derived with Solana because ED25519 SLIP-0010 does not support not-hardened derivation.

Regards,
Emanueke

**Comment by 123Serg** [comment]
>     * ED25519 SLIP-0010 does not support not-hardened derivation

Thank you for quick reply! What about number 4) ?

**Comment by ebellocchia** [comment]
I should check the code, it's very strange that it's derived using not-hardened indexes (but maybe they are).
Anyway, if they use a totally custom path, the only way to derive it is using BIP32 directly. I can provide an example but before I have to understand how they do it.

**Comment by 123Serg** [comment]
> 
> 
> I should check the code if available, it's very strange that it's derived using not-hardened indexes (but maybe they are). Also, it's not very clear to me what a "BIP-39 wallet" is, since BIP39 only specifies how to generate mnemonics and compute a seed from it, it doesn't specify anything about keys derivation (maybe they meant "BIP-32 wallet"). Anyway, if they use a totally custom path, the only way to derive it is using BIP32 directly. I can provide an example but before I have to understand how they do it.

Thank you so much for your help) If you can provide me example please, I'll make some tests too

**Comment by ebellocchia** [comment]
That m/0/0 path is deceiving, because Exodus prints it for all coins even if it's not the correct one. For example, for Ethereum it uses the complete BIP44 path (m/44'/60'/0'/0/0) but it prints m/0/0 in the private key window.

**Comment by 123Serg** [comment]
> That m/0/0 path is deceiving, because Exodus prints it for all coins even if it's not the correct one. For example, for Ethereum it uses the complete BIP44 path (m/44'/60'/0'/0/0) but it prints m/0/0 in the private key window.

Sooo disapointed, btw how can I use BIP32 for Solana and other coins with custom path?

**Comment by ebellocchia** [comment]
It's easy but it requires to use the correct BIP32 class depending on the coin curve (can be checked in the BIP44 configuration if not known) and the correct address encoding class.
For example, for Solana:

    import binascii
    from bip_utils import Bip32Ed25519Slip, Bip44Coins, Bip44, SolAddr

    seed_bytes = binascii.unhexlify(b"5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4")

    bip_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA).Purpose().Coin().Account(0)
    print(f"Address: {bip_ctx.PublicKey().ToAddress()}")

    # Same address as before
    bip_ctx = Bip32Ed25519Slip.FromSeed(seed_bytes)
    pub_key = bip_ctx.DerivePath("44'/501'/0'").PublicKey().KeyObject()
    print(f"Address: {SolAddr.EncodeKey(pub_key)}")

**Comment by 123Serg** [comment]
Thank you for help again and again. If you'll find some info about exodus solana derevation, I'll be happy to know about it

**Comment by ebellocchia** [comment]
I finally figured out how they do it. 
Basically, Exodus always uses the secp256k1 curve to derive the standard BIP44 path for all coins (even if they are not based on the secp256k1 curve) and, finally, it uses the last derived private key as a ed25519 private key.
It may sound strange (and, in fact, it doesn't follow any specification) but it's not the first time I saw something like this, because it avoids to implement other derivation schemes thus simplifying the code.
So, for Solana you can get the Exodus address like this:

    import binascii
    from bip_utils import Bip39SeedGenerator, Bip32Ed25519Slip, Bip32Secp256k1, SolAddr

    seed_bytes = binascii.unhexlify(b"5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4")

    # Derive the standard BIP44 path using secp256k1
    secp256k1_ctx = Bip32Secp256k1.FromSeed(seed_bytes).DerivePath("m/44'/501'/0'/0/0")
    priv_key_bytes = secp256k1_ctx.PrivateKey().Raw().ToBytes()

    # Use the last private key as a ed25519 key
    ed25519_ctx = Bip32Ed25519Slip.FromPrivateKey(priv_key_bytes)
    pub_key = ed25519_ctx.PublicKey().KeyObject()
    print(SolAddr.EncodeKey(pub_key))

**Comment by Fantom579** [comment]
Hi, unfortunately this does not work for Ontology (ONT)

**Comment by ebellocchia** [comment]
Yes you are right, Ontology and NEO use the nist256p1 curve and probably Exodus has another way to derive keys for those.
It should be checked in the Exodus source code or by contacting the support.

**Comment by josephawallace** [comment]
How about something like Cardano? They implement [BIP32-Ed25519](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjYlIyloKP3AhVNJt8KHezfCZsQFnoECAYQAQ&url=https%3A%2F%2Fraw.githubusercontent.com%2FLedgerHQ%2Forakolo%2Fmaster%2Fpapers%2FEd25519_BIP%2520Final.pdf&usg=AOvVaw2cG3GMblj3_Ic-ZIbDERi2) and support derivation of non-hardened children. In what ways is this proposed implementation not compatible with the Ed25519 derivation methods in this library?
