### ISSUE TITLE
Add Verge (XVG)

### ISSUE THREAD

**Issue by gittrekt** [ebellocchia/bip_utils#39]
Hi there. I appreciate the work, would you be able to add in Vergecoin and Signum? Thank-you

**Comment by ebellocchia** [comment]
Hi,
ok I'll take a look at it.

Emanuele

**Comment by gittrekt** [comment]
I appreciate that. I'm not in front of a computer at the moment but verge seemed relatively easy, using doge as an initial template I was able to find most values I needed to add it myself other than coin_idx. Are you able to give me some insight into what the coin IDX is?

**Comment by ebellocchia** [comment]
The coin index is the index defined by SLIP-0044 ("Coin type" column):

[https://github.com/satoshilabs/slips/blob/master/slip-0044.md](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

**Comment by gittrekt** [comment]
Thank you for the update. Do you know of a central place for the p2p and wif hex for other currencies? I'm interested in adding a few more smaller ones that lots won't be interested in, but I'm coming up short of finding those.

**Comment by ebellocchia** [comment]
If the coin is really small, usually the best thing is to look directly in the source code, there is always some files with the coin constants
