### ISSUE TITLE
invalid derived private key

### ISSUE THREAD

**Issue by spankders** [ebellocchia/bip_utils#40]
hello i am trying to get derived seed and private key of solana however when i call the private key from the library it gives me back an invalid private key which i cant use on any of solana wallets

```
from bip_utils import Bip44Coins, Bip44, Bip39SeedGenerator,Bip44Changes

seed_bytes = Bip39SeedGenerator('business visit gather camera cargo ketchup episode keep erosion pact large olympic amount trash bring heavy auto what merry surge motor quality corn okay').Generate()

bip44_def_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
bip44_acc_ctx = bip44_def_ctx.Purpose().Coin().Account(0)
bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
print("derived address : "+bip44_chg_ctx.PublicKey().ToAddress())
print("derived private key : "+bip44_chg_ctx.PrivateKey().ToExtended())
```

which output 
``` 
derived address : 93GqFeUXbtGGAP5GfTu6nBbZSvYTr1MiaCGsVpb8Dhk2
derived private key : xprvA1aUNWiGt1MiJQ17kARGhubHR8zEu49td9jMPEj7UigkbYXwxctNFEZrSE4htNrwR1tm7es8LCN9ubft8ah4VXmkcdT3mUBK9ynHsyL3yVB
 ```

the public key is correct but the private key isnt
also i cant see any way of getting a derived seed too

the valid private key is : `2SFFSyM8TqXBpsUNk6BbJkTZzkA2NJdHGLCNnYymWNAcgacJvc8PT9ZE4NsnUkgorbmhEk8tRdPcvvkAUTg6u3tA`

**Comment by ebellocchia** [comment]
Hi,
of course the private key is correct otherwise the public key and address won't be correct.
The fact is that every wallet requires the private key to be in its own specific format, so you have to "convert" the private key bytes to match it. You should check what format the wallet needs for importing the key. If you tell me the wallet name I can also check it.
Moreover, I suggest you to use the private key in hex format, because the extended format is very specific to BIP32 and not usually supported for being imported. Then you can convert it.

Regards

**Comment by spankders** [comment]
Thanks for the reply 
I'm trying to import the wallet to phantom wallet which require base58 or hex encoded private key but no matter what i do to the private key in the example the wallet seem to not accept it

**Comment by ebellocchia** [comment]
Ok, I'll check it as soon as I have some spare time

**Comment by ebellocchia** [comment]
Hi,
I checked the phantom wallet and, basically, the private key it requires is in reality the private key and the public key concatenated together and encoded in base58. 
So, you can easily get it as follows:

    from bip_utils import Bip44Coins, Bip44, Bip39SeedGenerator, Bip44Changes, Base58Encoder

    seed_bytes = Bip39SeedGenerator("business visit gather camera cargo ketchup episode keep erosion pact large olympic amount trash bring heavy auto what merry surge motor quality corn okay").Generate()

    bip44_def_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
    bip44_acc_ctx = bip44_def_ctx.Purpose().Coin().Account(0)
    bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
    print("derived address : "+bip44_chg_ctx.PublicKey().ToAddress())

    pub_key = bip44_chg_ctx.PublicKey().RawCompressed().ToBytes()[1:]
    priv_key = bip44_chg_ctx.PrivateKey().Raw().ToBytes()

    print("Encoded private key: " + Base58Encoder.Encode(priv_key + pub_key))

Regards,
Emanuele

**Comment by spankders** [comment]
thank you yeah now it works 
any idea how can i get the new seed too since we changed the path or does it stay the same

**Comment by ebellocchia** [comment]
I don't know what you mean with "we changed the path", but you cannot get back a seed from a private key
That seed you used in the sample code will always generate the same private key for that path (just remember that you are using: 44'/501'/0'/0')

**Comment by spankders** [comment]
my bad and thanks again for the help
