### ISSUE TITLE
coincurve no longer supports version 15

### ISSUE THREAD

**Issue by AndreaScorza** [ebellocchia/bip_utils#50]
subprocess.CalledProcessError: Command '['/private/var/folders/m8/gfy0lvq14bz9418x8bfd_zlc0000gn/T/pip-install-jankibtq/coincurve_876f93a8a1ad4e92bb612d15133fdc43/libsecp256k1/autogen.sh']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for coincurve 
  (while installing the package from pip)

Update the dependencies of the project to coincurve v16 please

**Comment by AndreaScorza** [comment]
found out the problem is with coincurve v15 hence not relevant to bip_utils, still a dependency update would be much appreciated

**Comment by AndreaScorza** [comment]
Yes, the problem for me at least seems to come from coincurve v15, my machine is running macOS with the M1 chip if that helps,

I've tried updating coincurve to v16 in the requirements.txt and built the new wheel but then the package breaks, so I believe coincurve v16 is not backward compatible to v15 hence a small refactor of the code to bring it up to date with v16 in my opinion would be required, 

Thank you

**Comment by ebellocchia** [comment]
No problem, I tried and I also got some problems with coincurve on MacOS with both version 15 and 16

**Comment by AndreaScorza** [comment]
In my case the error is `Symbol not found: _secp256k1_nonce_function_default` it's a C error, I'm missing the  `libsecp256k1` C library,
good luck

**Comment by ebellocchia** [comment]
Hi, the error was solved in coincurve version 17.0.0

**Comment by AndreaScorza** [comment]
Nice! 
Thank you
