### ISSUE TITLE
Is it possible to validate addresses

### ISSUE THREAD

**Issue by mehdiirh** [ebellocchia/bip_utils#51]
Hi. 
Is it possible to validate addresses of various assets with this module ?

**Comment by ebellocchia** [comment]
Hi,
not right now but it could be a nice feature to add, I'll do that

**Comment by mehdiirh** [comment]
Much appreciated

**Comment by mehdiirh** [comment]
Hello
how much time do you think it takes to add this feature ? :)

**Comment by ebellocchia** [comment]
Hi, I started to add address decoding in this branch:

[https://github.com/ebellocchia/bip_utils/tree/addr_decoding](https://github.com/ebellocchia/bip_utils/tree/addr_decoding)

**Comment by mehdiirh** [comment]
Thank you Emanuele, is there any docs for how to use address decoding ?

**Comment by ebellocchia** [comment]
Yes I'll update the README and examples as soon as it is completed

**Comment by ebellocchia** [comment]
I completed it, I hope it can be helpful
