### ISSUE TITLE
TypeError: Language is not an enumerative of Bip39Languages

### ISSUE THREAD

**Issue by Grantrocks** [ebellocchia/bip_utils#57]
Im testing a bruteforce script im makeing and i keep getting the following error.
`Traceback (most recent call last):
  File "/home/pi/betterbrute.py", line 30, in <module>
    if generate_address(words_prefix + list(perm)):
  File "/home/pi/betterbrute.py", line 13, in generate_address
    if not Bip39MnemonicValidator(mnemonic).Validate():
  File "/home/pi/.local/lib/python3.9/site-packages/bip_utils/bip/bip39/bip39_mnemonic_validator.py", line 50, in __init__
    self.m_mnemonic_decoder = Bip39MnemonicDecoder(lang)
  File "/home/pi/.local/lib/python3.9/site-packages/bip_utils/bip/bip39/bip39_mnemonic.py", line 303, in __init__
    self.m_words_list = (_Bip39WordsListGetter.Instance().GetByLanguage(lang)
  File "/home/pi/.local/lib/python3.9/site-packages/bip_utils/bip/bip39/bip39_mnemonic.py", line 164, in GetByLanguage
    raise TypeError("Language is not an enumerative of Bip39Languages")
TypeError: Language is not an enumerative of Bip39Languages`
Im using the latest version and my code is the following. I am pretty sure that my code is correct. And the following btc private keys and addresses were generated by iancolman.io/bip39
`from bip_utils import Bip39SeedGenerator, Bip39MnemonicValidator
from bip_utils import Bip44, Bip44Coins, Bip44Changes
import itertools

address = "1EHiMwCPzcvMdeGowsowVF2X2PgLo67Qj7"
words_prefix = ['since', 'desk']
words = ['zone', 'leaf', 'luggage', 'hobby', 'depart', 'thrive', 'practice', 'carbon', 'prison', 'ivory']

def generate_address(words):
    mnemonic = " ".join(words)
    # Early exit if the checksum word is wrong.
    if not Bip39MnemonicValidator(mnemonic).Validate():
        return False

    # Derive the seed bytes from the mnemonic.
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    # Derive the master BIP44 key from the seed bytes.
    bip44_mst = Bip44.FromSeed(seed_bytes, Bip44Coins.BITCOIN)
    # Derive account 0 for Bitcoin: m/44'/0'/0'.
    bip44_acc = bip44_mst.Purpose().Coin().Account(0)
    # Derive the external chain: m/44'/0'/0'/0
    bip44_change = bip44_acc.Change(Bip44Changes.CHAIN_EXT)
    # Derive the first address of the external chain: m/44'/0'/0'/0/0
    bip44_addr = bip44_change.AddressIndex(0)
    return bip44_addr.PublicKey().ToAddress() == address

for perm in itertools.permutations(words):
    if generate_address(words_prefix + list(perm)):
        print(words_prefix + list(perm))
        exit()
`

**Comment by ebellocchia** [comment]
Hi, 
when you validate a mnemonic you should pass it as argument of the method and not of the constructor, like:

    Bip39MnemonicValidator().Validate(mnemonic)

Moreover, the `Validate` function raises an exception if the mnemonic is not valid, so there is no need to use the "if".
If you need a boolean return value, use:

    Bip39MnemonicValidator().IsValid(mnemonic)

**Comment by Grantrocks** [comment]
Thank you for that. There there was nothing wrong with it. The code was for an older version.

**Comment by ebellocchia** [comment]
No problem. I also suggest you to specify the mnemonic language (if known in advance) in the constructor of the validator and seed generator, otherwise it's automatically detected so it's a little bit slower.
