### ISSUE TITLE
how can I get bip84 & bip141?

### ISSUE THREAD

**Issue by Gholbigrinn** [ebellocchia/bip_utils#58]
How can I get bip84 and bip141 adresses from seed phrase, can you give the code

**Comment by ebellocchia** [comment]
Hi,
there is an example in the _examples_ folder, just replace the mnemonic with your phrase:

[https://github.com/ebellocchia/bip_utils/blob/master/examples/bip84.py](https://github.com/ebellocchia/bip_utils/blob/master/examples/bip84.py)

Regards,
Emanuele

**Comment by Gholbigrinn** [comment]
thank you!
