### ISSUE TITLE
Problems installing bip_utils - Failed to build ed25519-blake2b

### ISSUE THREAD

**Issue by Anynomouss** [ebellocchia/bip_utils#59]
To my suprise I run into trouble installing bip_utils using `pip install bip_utils,` I got it to work in the past, so not sure what the issue is at the moment. Could it be that my Python to new or is this some sort compilatiopn error?

`bip_utils) (4.0.0)
Building wheels for collected packages: ed25519-blake2b
  Building wheel for ed25519-blake2b (setup.py): started
  Building wheel for ed25519-blake2b (setup.py): finished with status 'error'
  Running setup.py clean for ed25519-blake2b
Failed to build ed25519-blake2b
Installing collected packages: ed25519-blake2b, crcmod, bip-utils
    Running setup.py install for ed25519-blake2b: started
    Running setup.py install for ed25519-blake2b: finished with status 'error'`

**Comment by ebellocchia** [comment]
Hi, do you have Rust installed?

**Comment by Anynomouss** [comment]
rust updated: _rustup.exe_ 
microsoft visual C++ updated (_vs-buildtools_), 
setuptools updated (_pip3 install --upgrade setuptools_)
computer restarted, all to no avail. At least it indicates clearly it is problem with subpackage ed25519-blake2b, not a problem with bip-utils.

**Full error log here:**
Building wheels for collected packages: ed25519-blake2b
  Building wheel for ed25519-blake2b (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\keys.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\test_ed25519.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\_version.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\__init__.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      UPDATING build\lib.win-amd64-3.8\ed25519_blake2b/_version.py
      set build\lib.win-amd64-3.8\ed25519_blake2b/_version.py to '1.4'
      running build_ext
      building 'ed25519_blake2b._ed25519' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ed25519-blake2b
  Running setup.py clean for ed25519-blake2b
Failed to build ed25519-blake2b
Installing collected packages: ed25519-blake2b, crcmod, asn1crypto, pycryptodome, more-itertools, ecdsa, base58, scalecodec, coincurve, bip-utils
  Running setup.py install for ed25519-blake2b ... error
  error: subprocess-exited-with-error

  × Running setup.py install for ed25519-blake2b did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      C:\Python3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\keys.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\test_ed25519.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\_version.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      copying src\ed25519\__init__.py -> build\lib.win-amd64-3.8\ed25519_blake2b
      UPDATING build\lib.win-amd64-3.8\ed25519_blake2b/_version.py
      set build\lib.win-amd64-3.8\ed25519_blake2b/_version.py to '1.4'
      running build_ext
      building 'ed25519_blake2b._ed25519' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a sub-process, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ed25519-blake2b

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ebellocchia** [comment]
I remember that I solved the issue some time by installing the required C++ package.
Did you manage to solve the problem?

**Comment by Anynomouss** [comment]
No yet, I looked a lot online for similar problems and solutions. It is most likely some problem with the C++ packages not being detected by my various python environments, probably I need to adjust it or add it manually to the path. Since the problem is not bip-utils related, I will close this issue. If I find a solution that works for me, I will reopen, post it here and close the issue again

**Comment by ebellocchia** [comment]
Ok, I suggest you to open the issue directly on the ed25519-blake2b GitHub page: [https://github.com/Matoking/python-ed25519-blake2b](https://github.com/Matoking/python-ed25519-blake2b)
