### ISSUE TITLE
Conversions

### ISSUE THREAD

**Issue by mmorselli** [ebellocchia/bip_utils#60]
- The Ledger's BIP39 recovery phrase is a seed that along with an eventual passphrase generates a private key.
- The ALGORAND recovery phrase, however, directly encodes the private key. 

Can this library convert a Ledger recovery phrase to an ALGORAND recovery phrase? If yes, how?

**Comment by ebellocchia** [comment]
Hi,
unfortunately it is not possible (in general) to convert a BIP39 phrase to an Algorand one, because you should reverse the pbkdf2-sha512 algorithm and it is not feasible. The only thing you can do is recover the wallet from the private key.

Emanuele

**Comment by mmorselli** [comment]
Thank you Emanuele. But isn't Algorand's recovery phrase derived from the private key? 

https://community.algorand.org/blog/understanding-mnemonic-keys-and-how-they-are-generated-on-the-algorand-blockchain/

So having both the public key and the private key, I shouldn't be able to derive it?  (Forgive if the question is silly, my knowledge in this field is pretty basic)

**Comment by ebellocchia** [comment]
Let's recap in brief how it works:

- In Algorand wallet, the private key is just the random number (i.e. entropy) encoded by the 25-words
- In Ledger (i.e. BIP39), the private key is computed from the 12/24-words characters (not the random number) by computing the pbkdf2-sha512 and then the hmac-sha512

Therefore, if you have an Algorand private key and you want to find the correspondent Ledger's 12/24-words that generate it, you shall reverse the hmac-512 and pbkdf2-sha512, which is not feasible.

To make things more complicated:

- The Algorand walle uses the master private key, there is no derivation at all
- The Ledger derives the Algorand private key from the master one as specified in BIP32 and BIP44

So, even if you find by chance (which is basically impossible) the correspondent Ledger's words, you won't get the same Algorand address in the Ledger because it'll use private key derivation.

**Comment by mmorselli** [comment]
But then what is this tool supposed to do?

https://github.com/abmera/bip39toalgo

https://algorand.oortnet.com/

**Comment by ebellocchia** [comment]
Oh right, my bad, you can go from BIP39-words to Algorand-words, you just have to derive the final private key and encode it in the 25-words format. You cannot do the opposite (from Algorand to BIP39).
With this library it'd be like:

from bip_utils import (
        AlgorandMnemonicGenerator, Bip39WordsNum, Bip39MnemonicGenerator, Bip39SeedGenerator, Bip44Changes, Bip44Coins, Bip44
    )

    # Mnemonic
    mnemonic = "all all all all all all all all all all all all all all all all all all all all all all all feel"
    # Generate seed from mnemonic
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()

    # Construct from seed
    bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.ALGORAND)
    # Derive the address private key
    bip44_addr_ctx = bip44_mst_ctx.Purpose().Coin().Account(0).Change(Bip44Changes.CHAIN_EXT).AddressIndex(0)

    # Use the derived private key as entropy for Algorand mnemonic
    algo_mnemonic = AlgorandMnemonicGenerator().FromEntropy(bip44_addr_ctx.PrivateKey().Raw().ToBytes())
    print(f"Algorand mnemonic: {algo_mnemonic}")

You'll get the same mnemonic of the _bip39toalgo_ library.
I can add slip10-secp256k1 for Algorand if you need. kholaw-ed25519 is not currently supported.

**Comment by mmorselli** [comment]
Thank you very much! Unfortunately I guess that kholaw-ed25519 is required for Ledger, but the confirmation that it's not impossible, but just an implementation issue is a valuable info.

**Comment by ebellocchia** [comment]
Actually it seems strange to me because Algorand should follow the slip10-ed25519, but it may be possible that the Ledger does it differently (every wallet can do what it wants in the end).

**Comment by mmorselli** [comment]
I actually made this assumption just because selecting Ledger on https://algorand.oortnet.com/ the kholaw-ed25519 derivation method is autoselected. I didn't try it on a Ledger just because before buying one I need to be sure that in case of device failure I could access my funds without waiting for a new device.

**Comment by ebellocchia** [comment]
Hi,
I implemented the Bip32-Kholaw derivation scheme.
Now you can find the same functionality of that website in this example: [https://github.com/ebellocchia/bip_utils/blob/master/examples/bip39_to_algorand.py](https://github.com/ebellocchia/bip_utils/blob/master/examples/bip39_to_algorand.py)

Regards,
Emanuele
