### ISSUE TITLE
Bech32 address generation

### ISSUE THREAD

**Issue by vmsh0** [ebellocchia/bip_utils#7]
Hello,

Does BipPublicKey support generating a Bech32 address?

**Comment by ebellocchia** [comment]
Hello,
the Bech32 address depends on the coin. There are 3 classes for it:

- *AtomBech32Encoder*/*AtomBech32Decoder* : Cosmos Bech32 addresses
- *BchBech32Encoder*/*BchBech32Decoder* : BitcoinCash Bech32 addresses
- *SegwitBech32Encoder*/*SegwitBech32Decoder* : Bitcoin Bech32 addresses

They can be used directly or, more easily, through the address generation classes:

- *AtomAddr* : generate a Cosmos Bech32 address from the public key
- *BchP2PKH* : generate a BitcoinCash Bech32 address from the public key
- *P2WPKH* : generate a Bitcoin Bech32 address from the public key

Their usage is described in the **Addresses generation** paragraph in the main page.
