### ISSUE TITLE
Use Bip44 on solana-py KeyPair()

### ISSUE THREAD

**Issue by DanKamilov** [ebellocchia/bip_utils#70]
Hello! How to get seed with derived path "m/44'/501'/0'/0'" for using in KeyPair.from_seed() from solana-py library?

I see my phantom wallet address only after:
bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(0)
bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
print(f"Address: {bip44_chg_ctx.PublicKey().ToAddress()}")

But how to get deriveSeed (derive_seed_bytes) for KeyPair? I need this to make transactions.

**Comment by ebellocchia** [comment]
Hi, I've never used solana-py.
Can you tell me what result does KeyPair.from_seed return? Or, provide me a snippet that I can run to check it?

Thanks
Emanuele

**Comment by DanKamilov** [comment]
> Hi, I've never used solana-py. Can you tell me what result does KeyPair.from_seed return? Or, provide me a snippet that I can run to check it?
> 
> Thanks Emanuele

yes. https://github.com/michaelhly/solana-py (especially KeyPair class https://michaelhly.github.io/solana-py/core/keypair/) you can check it here. It is a main Python Solana library now. 
KeyPair returns keypair from seed. It works fine but my public key does not equal my phantom wallet address. I need to use derive_sees_bytes array buy I don't know how to generate it from mnemonic.

**Comment by DanKamilov** [comment]
> Hi, I've never used solana-py. Can you tell me what result does KeyPair.from_seed return? Or, provide me a snippet that I can run to check it?
> 
> Thanks Emanuele

and here is a code snippet for testing

`from solana.rpc.api import Client
from solana.keypair import Keypair
from bip_utils import *

#how to use der_path to get der_seed_bytes array?
phantomAndSolletDerPaths = "m/44'/501'/0'/0'"

#creating solana client
client = Client("https://api.devnet.solana.com")

#creating seed_bytes (without derive path)
seed_bytes = Bip39SeedGenerator("mnemonic words here").Generate("")

keypair_account = Keypair.from_seed(seed_bytes[slice(0,32)])

#check that Phantom wallet address and public key are equal
print(keypair_account.public_key)

#check sol balance
balanceSol = client.get_balance(keypair_account.public_key)
print("SOL: " + str(balanceSol['result']['value']/1000000000))`

**Comment by DanKamilov** [comment]
It Very helps! Thank you!
