### ISSUE TITLE
Cannot (fully) restore Bip32Secp256k1 from Secp256k1PrivateKey

### ISSUE THREAD

**Issue by tdiesler** [ebellocchia/bip_utils#71]
I'm trying restore a Bip32Secp256k1 context from a Secp256k1PrivateKey. This fails because the code does not restore the chain code and fingerprints correctly

```
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()

bip32_ctx1 = Bip32Secp256k1.FromSeedAndPath(seed_bytes, "m/44'/60'/0'/0")
bip32_prvkey1 = bip32_ctx1.PrivateKey()
bip32_pubkey1 = bip32_ctx1.PublicKey()

# Print other BIP32 data
print(bip32_ctx1.Index().ToInt())
print(bip32_ctx1.Depth().ToInt())
print(bip32_ctx1.ChainCode().ToHex())
print(bip32_ctx1.FingerPrint().IsMasterKey())
print(str(bip32_ctx1.FingerPrint()))
print(bip32_ctx1.ParentFingerPrint().IsMasterKey())
print(str(bip32_ctx1.ParentFingerPrint()))

secp256k1_prvkey = Secp256k1PrivateKey.FromBytes(bytes(bip32_prvkey1.Raw()))
assert bip32_prvkey1.Raw().ToHex() == secp256k1_prvkey.Raw().ToHex()

bip32_ctx2 = Bip32Secp256k1.FromPrivateKey(bytes(secp256k1_prvkey.Raw()))
bip32_ctx2 = bip32_ctx2.DerivePath("m/44'/60'/0'/0")
bip32_prvkey2 = bip32_ctx2.PrivateKey()
bip32_pubkey2 = bip32_ctx2.PublicKey()
# assert bip32_prvkey1.Raw().ToHex() == bip32_prvkey2.Raw().ToHex()
# assert bip32_pubkey1.RawCompressed().ToHex() == bip32_pubkey2.RawCompressed().ToHex()

# Print other BIP32 data
print()
print(bip32_ctx2.Index().ToInt())
print(bip32_ctx2.Depth().ToInt())
print(bip32_ctx2.ChainCode().ToHex())
print(bip32_ctx2.FingerPrint().IsMasterKey())
print(str(bip32_ctx2.FingerPrint()))
print(bip32_ctx2.ParentFingerPrint().IsMasterKey())
print(str(bip32_ctx2.ParentFingerPrint()))
```

Here the print output ...

```
0
4
c879d136f02003dc804811e42390714ea06448aeaee158c62d65f12a421d988f
False
e4389614
False
60b68b69

0
4
c7d5faabfe9e8aeb976a7bc1d65a64d6749c29243aac0d676e6f357ff0126c3d
False
4b89e1b1
False
8e9ef2a3
```

Is there a way to do this round-trip via Secp256k1PrivateKey, which I need for Bip38 encryption

**Comment by ebellocchia** [comment]
Hi,
that's normal and there is also written in the `FromPrivateKey` method docstring:

    @classmethod
    def FromPrivateKey(cls,
                       priv_key: Union[bytes, IPrivateKey],
                       key_net_ver: Bip32KeyNetVersions = Bip32Const.MAIN_NET_KEY_NET_VERSIONS) -> Bip32Base:
        """
        Create a Bip32 object from the specified private key.
        The key will be considered a master key with the chain code set to zero,
        since there is no way to recover the key derivation data.

A private key is only a raw 32-byte key, so it doesn't contain the BIP32 derivation data (i.e. child index, chaincode and fingerprints). Therefore, if you import it, it'll be always considered a master key with all the derivation data set to zero (there is no way around it). The associated address will be correct, but the derivation data will be missing so you cannot derive the correct child keys (they will be different).
The only way to maintain the BIP32 derivation data is to use the extended private key.

If you want to export to WIF or BIP38 format and being able to recover it, you shall export the private key of the BIP44 address index, not the master key (that's what Electrum does when you export private keys).

Regards,
Emanuele

**Comment by ebellocchia** [comment]
Ok, I think I got the point.
In order to restore a private key and correctly derive the child keys, you only need to store two things:

- The private key bytes
- The chain code bytes

That's it. The other metadata (i.e. child index and fingerprints) is not strictly needed, unless you also want to get back the original xprv key.
The chain code shall always be stored, even if it's a master key, because it's never equal to zero (setting it to zero in the `FromPrivateKey` method is just to give it a fixed value).

So, I'd say:

- If you only need to derive the child keys:
  -  Just store the BIP38-encrypted private key and the chain code (no need to encrypt it). You can set the child index and parent fingerprint to zero (it'll be a master key, in that case).
 - If you also want to restore the original xprv key:
   - Store the BIP38-encrypted private key, the chain code, the child index and the parent fingerprint.

I can also add an optional chain code parameter to the `FromPrivateKey` method, I think it makes sense.

**Comment by tdiesler** [comment]
Great. I need to restore an xprv... key in a way that allows me to derive child keys. Currently, this happens at the account level. The config file shall not contain information that could give access to sibling trees at the same level (i.e. to other accounts)

Yes, improving the API an having an example would be great - cheers

**Comment by ebellocchia** [comment]
Hi,
I added optional parameters to the `FromPrivateKey` and `FromPublicKey` methods for recovering the full metadata if needed.
For example, you can do:

    from bip_utils import Bip39SeedGenerator, Bip32Secp256k1, Bip38Decrypter, Bip38Encrypter
    
    mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    
    bip32_ctx = Bip32Secp256k1.FromSeed(seed_bytes)
    
    print("Original:")
    print(bip32_ctx.PublicKey().ToExtended())
    print(bip32_ctx.PrivateKey().ToExtended())
    print("")
    
    # Get data
    priv_key_enc = Bip38Encrypter.EncryptNoEc(bip32_ctx.PrivateKey().KeyObject(), "passphrase")
    chain_code = bytes(bip32_ctx.ChainCode())
    depth = int(bip32_ctx.Depth())
    index = int(bip32_ctx.Index())
    fprint = bytes(bip32_ctx.FingerPrint())
    # Store it somewhere...
    
    # Restore
    bip32_restored_ctx = Bip32Secp256k1.FromPrivateKey(
        Bip38Decrypter.DecryptNoEc(priv_key_enc, "passphrase")[0],
        chain_code=chain_code,
        depth=depth,
        index=index,
        fprint=fprint
    )
    
    print("Restored:")
    print(bip32_ctx.PublicKey().ToExtended())
    print(bip32_ctx.PrivateKey().ToExtended())

**Comment by tdiesler** [comment]
Works great - thanks
