### ISSUE TITLE
Add electrum

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#72]
PLS ADD support generate mnemonic and create address electrum v1 (old 100000*sha256) , v2 standart

**Comment by ebellocchia** [comment]
Ok, I'll check it

**Comment by Noname400** [comment]
Thanks. I will be very waiting

**Comment by Noname400** [comment]
I can hope for a positive decision ?

**Comment by ebellocchia** [comment]
Yes I've already created the branch [https://github.com/ebellocchia/bip_utils/tree/electrum_mnemonic](https://github.com/ebellocchia/bip_utils/tree/electrum_mnemonic)

**Comment by Noname400** [comment]
Thank you so much. looking forward to your product!

**Comment by ebellocchia** [comment]
Hi,
I merged the branch, you can an Electrum example [here](https://github.com/ebellocchia/bip_utils/blob/master/examples/electrum.py).

Docs:
- [Electrum V1 mnemonics](https://github.com/ebellocchia/bip_utils/blob/master/readme/electrum_v1_mnemonic.md)
- [Electrum V2 mnemonics](https://github.com/ebellocchia/bip_utils/blob/master/readme/electrum_v2_mnemonic.md)
- [Electrum keys derivation](https://github.com/ebellocchia/bip_utils/blob/master/readme/electrum.md)

**Comment by Noname400** [comment]
You are wonderful. thanks a lot
