### ISSUE TITLE
I'm having issues importing Bip49 and Bip89

### ISSUE THREAD

**Issue by Dfclay** [ebellocchia/bip_utils#73]
From the example folder. I use python 3.6.2

Please I will really appreciate

**Comment by ebellocchia** [comment]
Hi, the minimum required Python version is 3.7

**Comment by Dfclay** [comment]
Thank you I'm gonna do that now.

**Comment by Dfclay** [comment]
I have updated my python to python 3.7.1 and have issues installing bip_utils which install in my previous python

**Comment by ebellocchia** [comment]
Hi, if you don't paste here the error I cannot help you

**Comment by Dfclay** [comment]
I will paste that now

**Comment by ebellocchia** [comment]
You can also check this if it's the same: [https://github.com/ebellocchia/bip_utils/issues/59](https://github.com/ebellocchia/bip_utils/issues/59)

**Comment by Dfclay** [comment]
Yes that exactly what I'm facing. I'm going to try the solution there.

**Comment by ebellocchia** [comment]
Ok, perfect
