### ISSUE TITLE
Add Axelar

### ISSUE THREAD

**Issue by 3venturesio** [ebellocchia/bip_utils#75]
Hi,
Would you mind adding support for generating Axelar (https://axelar.network/) addresses?

Prefix is: axelar

https://docs.axelar.dev/resources

Thank you in advance

**Comment by ebellocchia** [comment]
Hi,
yes sure, if it's based on the Cosmos SDK it should be pretty straightforward.
Do you also know the coin index?

Thanks

**Comment by 3venturesio** [comment]
Yes, it's cosmos SDK based.

No idea about the coin index but found this https://github.com/Zondax/ledger-axelar/pull/14/files that might give some clues

**Comment by ebellocchia** [comment]
Yes it's the same in Cosmostation, I'll add it once Electrum si finished.

**Comment by 3venturesio** [comment]
Thanks,
I was giving it a try:

![image](https://user-images.githubusercontent.com/97380979/175926435-5a9cc290-106a-49d6-97d1-3cb3cd054214.png)

I did install from git, that resolved to a later commit:

![image](https://user-images.githubusercontent.com/97380979/175926559-5060397a-680a-46dd-818f-9831fb7b225f.png)


Code I was testing:
~~~py
import bip_utils
mnemo="talent theory online tired convince toast need dumb style prosper outer wine unable access shoe fresh borrow toddler embody wedding music victory noise purchase"
seed_bytes = bip_utils.Bip39SeedGenerator(mnemo).Generate()
bip44_def_ctx = bip_utils.Bip44.FromSeed(seed_bytes, bip_utils.Bip44Coins.AXELAR).DeriveDefaultPath()
~~~

Did I miss something? TYIA

**Comment by ebellocchia** [comment]
Hi,
it's not in a release but the current repo shall work with that code, also because Axelar is in the tests and they are all passing
