### ISSUE TITLE
Mnomic doesn't match with solana wallet

### ISSUE THREAD

**Issue by devlancer412** [ebellocchia/bip_utils#78]
I tried to get all wallet addresses from Mnomic. But it doesn't match solana wallet address.
This is my  code
```
  seed_bytes = Bip39SeedGenerator(cfg.ETH_TEMP_MNEMONIC).Generate()
  bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
  bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(0)
  for i in range(100):
    bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT).AddressIndex(i)

    new_wallet = WalletData()
    new_wallet.public_key = bip44_chg_ctx.PublicKey().ToAddress()
    new_wallet.private_key = bip44_chg_ctx.PrivateKey().ToExtended()
```

And How I can get private key string like phantom wallet?

**Comment by ebellocchia** [comment]
Hi,
Phantom wallet uses m/44'/501'/0'/0' as derivation path, so you should stop at the change level and, to generate multiple addresses, you should increase the account index:

    mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
    bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
    
    for i in range(5):
        bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(i)
        bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
        # Same as Phantom wallet
        print(bip44_chg_ctx.PublicKey().ToAddress())

Regards,
Emanuele
