### ISSUE TITLE
ECDSA compability

### ISSUE THREAD

**Issue by ctrl-Felix** [ebellocchia/bip_utils#79]
The current version(s) are only compatible with ecdsa 0.15. This is interfering with the polkadot substrate-interface library which requires ecdsa >= 0.17

Would it be possible to change the ecdsa version or is this creating compatibility problems inside bip_utils?

**Comment by ebellocchia** [comment]
No, it's not like that.
The dependency is `ecdsa~=0.15`, which means that any version >=0.15 and <1.0.0 is fine

**Comment by ctrl-Felix** [comment]
> No, it's not like that. The dependency is `ecdsa~=0.15`, which means that any version >=0.15 and <1.0.0 is fine

I'm stupid, lol. Thanks for clarifying. Anyways it was another library that caused the dependency issue...
