### ISSUE TITLE
Was unable to install package (fix proposal)

### ISSUE THREAD

**Issue by DaniZaha** [ebellocchia/bip_utils#82]
I tried to install this package with pip but it failed (error text in attached file).
[error_text.txt](https://github.com/ebellocchia/bip_utils/files/9305432/error_text.txt)

Fixed by editing setup.py. Added encoding='utf-8' on line 11 (see second attached file)
[setup.txt](https://github.com/ebellocchia/bip_utils/files/9305439/setup.txt)

**Comment by ebellocchia** [comment]
Hi,
thank you very much for the finding, I'll update it.

Regards,
Emanuele
