### ISSUE TITLE
Polygon coin id error?

### ISSUE THREAD

**Issue by panqingfeng** [ebellocchia/bip_utils#92]
coin_idx should be 966 but not coin_idx=Slip44.ETHEREUM ?
   
 # Configuration for Polygon
    Polygon: BipCoinConf = BipCoinConf(
        coin_names=CoinsConf.Polygon.CoinNames(),
        coin_idx=Slip44.ETHEREUM,
        is_testnet=False,
        def_path=NOT_HARDENED_DEF_PATH,
        key_net_ver=_BIP44_BTC_KEY_NET_VER_MAIN,
        wif_net_ver=None,
        bip32_cls=Bip32Slip10Secp256k1,
        addr_cls=EthAddrEncoder,
        addr_params={},
    )

**Comment by ebellocchia** [comment]
Hi,
Matic is EVM compatible so it has the same addresses of ETH, unless something changed
