### ISSUE TITLE
How to derive BTC address from BIP39?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [ebellocchia/bip_utils#95]
It's not stated in the README. I checked the source code for the word "derived" but didn't found anything related to this simple question.

How to derive BTC public address(es) and other coins addresses of the wallet from BIP39 seed phrase?

**Comment by ebellocchia** [comment]
Hi, 
you find example in the [examples](https://github.com/ebellocchia/bip_utils/tree/master/examples) folder, check bip44/49/84

Regards
Emanuele
