### ISSUE TITLE
ImportError: cannot import name 'Bip44Ethereum' from 'bip_utils.bip.conf.bip44'

### ISSUE THREAD

**Issue by yungsucc** [ebellocchia/bip_utils#98]
Error:
Traceback (most recent call last):
  File "c:/Users/frede/OneDrive/Desktop/Logs tools/seed_parser_v2.2/gen_wallet.py", line 3, in <module>
    from bip_utils.bip.conf.bip44 import Bip44Ethereum
ImportError: cannot import name 'Bip44Ethereum' from 'bip_utils.bip.conf.bip44' (C:\Users\frede\AppData\Local\Programs\Python\Python38\lib\site-packages\bip_utils\bip\conf\bip44\__init__.py)
PS C:\Users\frede> 
Ive tried everything to fix this, but nothing works.

**Comment by ebellocchia** [comment]
Hi,
I don't know where you found Bip44Ethereum because it doesn't exist and it's not mentioned in the doc, maybe you were using an older version before?
